#
#debug: false
#
#
#server:
#  port: 80
#  servlet:
#    context-path: /api
#    encoding:
#      charset: utf-8
#
##logging.level.org.springframework=DEBUG
#
#spring:
#  application:
#    name: system-management
#  main:
#    allow-bean-definition-overriding: true
#  aop:
#    auto: true
#    proxy-target-class: true
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: false # \u542F\u7528hiddenMethod\u8FC7\u6EE4\u5668
#  servlet:
#    multipart:
#      max-file-size: 20MB # \u5355\u4E2A\u6587\u4EF6\u7684\u6700\u5927\u957F\u5EA6
#      max-request-size: 200MB # \u5355\u4E2A\u8BF7\u6C42\u7684\u6700\u5927\u957F\u5EA6
#  data:
#    rest:
#      default-page-size: 10
#      max-page-size: 1000
#      page-param-name: pageNum
#      limit-param-name: pageSize
#      sort-param-name: orderBy
#
#  # 数据库
#  datasource:
#    url-prefix: jdbc:mysql://192.168.1.203:53306 # database connect
#    name: test
#    url: ${spring.datasource.url-prefix}/${spring.datasource.name}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
#    username: root
#    password: hsrg8888
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    #driver-class-name=org.mariadb.jdbc.Driver
#
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    #database-platform: org.hibernate.dialect.MariaDB103Dialect
#hibernate:
#  hbm2ddl:
#    auto: update
#
#
## data source
#spring:
#  datasource:
#    druid:
#      initialSize: 1
#      minIdle: 1
#      maxActive: 20
#      maxWait: 60000
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: SELECT 1
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 20
#      maxPoolPreparedStatementPerConnectionSize: 20
##      filters: stat,wall,mergeStat,log4j
##      filters: stat,mergeStat,wall
#      filters: stat,mergeStat
#      web-stat-filter:
#        enabled: true
##      useGlobalDataSourceStat: true
##      log-abandoned: true
## \u662F\u5426\u542F\u52A8\u5B58\u5728\u7684\u8C03\u5EA6\u4EFB\u52A1
#spring.quartz.task.start-up=true
#
## print log
##logging.level.com.benefitj.scaffold.quartz.mapper=DEBUG
##logging.level.com.benefitj.system.mapper=DEBUG
##logging.level.com.benefitj.system=DEBUG
##mybatis
#mybatis.type-aliases-package=com.benefitj.system.model
#mybatis.mapper-locations=classpath:mapper/*.xml
#mybatis.configuration.map-underscore-to-camel-case=true
##mappers \u591A\u4E2A\u63A5\u53E3\u65F6\u9017\u53F7\u9694\u5F00
#mapper.mappers=com.benefitj.scaffold.mapper.SuperMapper,tk.mybatis.mapper.common.Mapper
#mapper.not-empty=true
#mapper.identity=MYSQL
#mapper.style=camelhump
#
##pagehelper
#pagehelper.helperDialect=mysql
#pagehelper.reasonable=true
#pagehelper.supportMethodsArguments=true
#pagehelper.params=count=countSql
#
############# quartz ######################################################
##spring.quartz.scheduler-name=QRTZ-Scheduler
##spring.quartz.auto-startup=true
##spring.quartz.jdbc.schema=classpath:org/quartz/impl/jdbcjobstore/tables_mysql_innodb.sql
#spring.quartz.jdbc.initialize-schema=EMBEDDED
##spring.quartz.jdbc.comment-prefix=QRTZ_
##spring.quartz.overwrite-existing-jobs=false
##spring.quartz.job-store-type=JDBC
##spring.quartz.wait-for-jobs-to-complete-on-shutdown=true
##spring.quartz.startup-delay=1s
#spring.quartz.datasource.driver-class-name=${spring.datasource.driver-class-name}
## \u914D\u7F6E\u6570\u636E\u6E90(\u6570\u636E\u5E93)
##spring.quartz.datasource.url=${spring.datasource.url}
#spring.quartz.datasource.url=${spring.datasource.url-prefix}/quartz?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
#spring.quartz.datasource.username=${spring.datasource.username}
#spring.quartz.datasource.password=${spring.datasource.password}
#
#
############# redis ######################################################
#spring.redis.host=192.168.1.203
#spring.redis.port=56379
#spring.redis.password=
#spring.redis.timeout=10000ms
#spring.redis.lettuce.pool.max-active=16
#spring.redis.lettuce.pool.max-idle=8
#spring.redis.lettuce.pool.max-wait=1000ms
#spring.redis.lettuce.pool.min-idle=0
#spring.redis.lettuce.shutdown-timeout=100ms
#spring.redis.database=0
#
############# jwt ######################################################
## 30 minutes
##spring.security.jwt.expiration=1800
#spring.security.jwt.expiration=604800
## 7 days
#spring.security.jwt.refresh-expiration=604800
#spring.security.jwt.issuer=benefitj
#spring.security.jwt.signing-key=CtJfeCGoJx0jZkAyqUmaRYjraqAWSGHvj3knb9Ust7dqa89Ip1p7wHqdY35cT5isXJTLAy+zynCZPLY6Gwz73Q==
############# url ######################################################
## \u5FFD\u7565\u8DEF\u5F84\u7684\u8BA4\u8BC1
#spring.security.url.ignore-path=/auth/**,/documentation/**
#
############################################################
### swagger-ui
#logging.level.springfox.documentation=INFO
#springfox.documentation.swagger-ui.base-url=/documentation
#springfox.documentation.swagger.v2.use-model-v3=true
#spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
### knife4j
#knife4j.enable=true
#knife4j.setting.enableFooter=false
#knife4j.setting.enableFooterCustom=true
#knife4j.setting.footerCustomContent=Apache License 2.0 | Copyright  2022-[Hello World](https://localhost:${server.port}${server.servlet.context-path}/knife4j)
#
#
## system root file
#com.benefitj.file-manager.root=/opt/apps/data/
## PDF
## athenapdf \u4EA7\u751F\u7684PDF\u6587\u4EF6\u7F13\u5B58
#spring.athenapdf.cache-dir=/opt/apps/data/pdf
## athenapdf \u6620\u5C04\u76EE\u5F55
#spring.athenapdf.volume-dir=/opt/apps/system-management/data/pdf
## \u4FDD\u5B58\u65F6\u957F
#spring.athenapdf.delay=120
#
############# rbac ######################################################
## check org level
#com.benefitj.security.rbac.check-org-level=true
#
############# log ######################################################
## \u4FDD\u5B58\u8BF7\u6C42\u65E5\u5FD7
#spring.aop.operation-log.save=true
## \u662F\u5426\u5FFD\u7565GET\u8BF7\u6C42
#spring.aop.operation-log.ignore-get=true
## \u5FFD\u7565\u4FDD\u5B58\u7684\u8DEF\u5F84\uFF0C\u4F7F\u7528\u9017\u53F7\u5206\u5272
#spring.aop.operation-log.ignore-urls=/**/auth
## \u6253\u5370\u65E5\u5FD7
#spring.aop.http-logging.print=true
## \u6253\u5370\u591A\u884C\u65E5\u5FD7
#spring.aop.http-logging.multi-line=false
#
